version: "3.8"

services:
  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server:21.11

    ports:
      - 8123:8123
      - 9000:9000

    volumes:
      - clickhouse_db:/var/lib/clickhouse

volumes:
  clickhouse_db:
